### PR TITLE
Adding query args filter

### PR DESCRIPTION
**Pull request by hlashbrooke**
Adding `eventorganiser_posterboard_query_args` filter for ajax query args.

### CODE REVIEW

**Comment by hlashbrooke** [comment]
I simply added a filter on line 218 - no idea why all of those other lines have supposedly been edited. Apologies if that makes this PR difficult, but I didn't even touch those lines at all.

**Comment by stephenharris** [comment]
That's odd :/, I'll add this in myself to keep things clean. I'll leave this open to remind myself, but I shall add this for the next update.

I'll probably add a `$query['context']` so that the query can be targeted at `pre_get_posts` too.

**Comment by stephenharris** [comment]
Please note the change of hook name (for consistency with https://github.com/stephenharris/Event-Organiser/commit/d01193c4b11934513bf48b9618b4da7632a88388)

**Comment by hlashbrooke** [comment]
Great stuff - thanks for merging so quickly :)

**Pull request closed without merging**
